/**
 * templates.ts — Embedded content for all files generated by `pi-thoth-config init`.
 *
 * No I/O at template time. Every template is a pure string or function.
 */

// ---------------------------------------------------------------------------
// MCP config — .omp/mcp.json
// ---------------------------------------------------------------------------

export const MCP_SERVER_KEY = "th0th";

export interface McpServer {
  type: string;
  command: string;
  args: string[];
  enabled: boolean;
  timeout: number;
}

export interface McpConfig {
  servers: Record<string, McpServer>;
  [key: string]: unknown;
}

export const defaultMcpServer: McpServer = {
  type: "stdio",
  command: "bunx",
  args: ["pi-thoth"],
  enabled: true,
  timeout: 30,
};

// ---------------------------------------------------------------------------
// OMP settings — .omp/settings.json
// ---------------------------------------------------------------------------

export interface OmpSettings {
  skills?: {
    enabled?: boolean;
    enableSkillCommands?: boolean;
    [key: string]: unknown;
  };
  [key: string]: unknown;
}

export const defaultOmpSettings: OmpSettings = {
  skills: {
    enabled: true,
    enableSkillCommands: true,
  },
};

// ---------------------------------------------------------------------------
// th0th-memory SKILL.md — .omp/skills/th0th-memory/SKILL.md
// ---------------------------------------------------------------------------

export const SKILL_TEMPLATE = `---
name: th0th-memory
description: Mandatory rules for using th0th semantic search, compression, and memory tools. Prioritize th0th tools over native tools (Glob, Grep, Read) to explore and understand code. Triggers on tasks involving code search, context compression, storing decisions, or retrieving project knowledge.
license: MIT
metadata:
  author: S1LV4
  version: "1.0.0"
---

# th0th-memory Skill

Mandatory rules for using th0th tools. Prioritize semantic search, compression, and memory over native tools (Glob, Grep, Read) to explore and understand code.

## When to Apply

Reference these guidelines when:
- Searching for code patterns or implementations
- Understanding codebase architecture
- Storing important decisions or patterns
- Compressing large code contexts
- Retrieving memories from previous sessions
- Analyzing usage and performance metrics

## Available Tools

| Priority | Tool | Use |
|----------|------|-----|
| 1 | \`th0th_index\` | Index project before searching |
| 2 | \`th0th_search\` | Semantic + keyword search with filters |
| 3 | \`th0th_optimized_context\` | Search + compress in one call |
| 4 | \`th0th_remember\` | Store important information |
| 5 | \`th0th_recall\` | Retrieve memories from previous sessions |
| 6 | \`th0th_compress\` | Reduce context size (70-98%) |
| 7 | \`th0th_analytics\` | Usage patterns and metrics |
| 8 | Glob/Grep/Read | Only when th0th doesn't find |

## Tool Reference

### 1. th0th_index

Index a project directory for semantic search.

\`\`\`
th0th_index({
  projectPath: "/home/user/my-project",
  projectId: "my-project",
  forceReindex: false,
  warmCache: true
})
\`\`\`

### 2. th0th_search

Semantic + keyword search with RRF (Reciprocal Rank Fusion).

\`\`\`
th0th_search({
  query: "JWT authentication middleware",
  maxResults: 10,
  minScore: 0.3,
  include: ["src/**/*.ts"],
  exclude: ["**/*.test.*"]
})
\`\`\`

### 3. th0th_optimized_context

Search + compress in one call. Maximum token efficiency.

\`\`\`
th0th_optimized_context({
  query: "how does authentication work?",
  maxTokens: 4000,
  maxResults: 5
})
\`\`\`

### 4. th0th_remember

Store important information in persistent memory.

\`\`\`
th0th_remember({
  content: "Using PostgreSQL for user data",
  type: "decision",
  importance: 0.8,
  tags: ["database", "architecture"]
})
\`\`\`

### 5. th0th_recall

Search stored memories from previous sessions.

\`\`\`
th0th_recall({
  query: "database decisions",
  types: ["decision"],
  limit: 10,
  minImportance: 0.3
})
\`\`\`

### 6. th0th_compress

Compress context (keeps structure, removes details).

\`\`\`
th0th_compress({
  content: "...large code...",
  strategy: "code_structure",
  targetRatio: 0.7
})
\`\`\`

### 7. th0th_analytics

Usage patterns, cache performance, metrics.

\`\`\`
th0th_analytics({
  type: "summary",
  limit: 10
})
\`\`\`

## Compression Strategies

| Strategy | Use Case | Reduction |
|----------|----------|-----------|
| \`code_structure\` | Source code | 70-90% |
| \`conversation_summary\` | Chat history | 80-95% |
| \`semantic_dedup\` | Repetitive content | 50-70% |
| \`hierarchical\` | Structured docs | 60-80% |

## Memory Types

| Type | Use |
|------|-----|
| \`preference\` | User preferences |
| \`conversation\` | Important conversation points |
| \`code\` | Code patterns discovered |
| \`decision\` | Architecture decisions |
| \`pattern\` | Recurring patterns |

## Decision Flow

\`\`\`
Need to find code?
  → th0th_search (first)
  → Glob/Grep/Read (fallback)

Need to understand architecture?
  → th0th_recall (check memories first)
  → th0th_search (explore code)

Found important pattern/decision?
  → th0th_remember (store for future)

Context too large?
  → th0th_compress (reduce tokens)

Maximum efficiency needed?
  → th0th_optimized_context (search + compress)
\`\`\`
`;

// ---------------------------------------------------------------------------
// Auto-index extension — .omp/extensions/th0th-auto-index/index.ts
// Always written (overwrite) so users get the latest version.
// ---------------------------------------------------------------------------

export const AUTO_INDEX_EXTENSION_TEMPLATE = `// th0th-auto-index extension
// Auto-generated by pi-thoth-config init — safe to commit.
// Re-run \`pi-thoth-config init\` to update to the latest version.
export default function (pi: any) {
  pi.setLabel("th0th Auto-Index");

  pi.on("session_start", async (_event: any, ctx: any) => {
    const fs = await import("fs");
    const path = await import("path");
    const dataDir = path.join(ctx.cwd, ".th0th", "data");

    // vector-store.db is created by th0th_index on first run
    const hasIndex = fs.existsSync(path.join(dataDir, "vector-store.db"));

    if (!hasIndex) {
      pi.sendMessage(
        {
          role: "user",
          content: [
            {
              type: "text",
              text:
                "This project has not been indexed by th0th yet. " +
                "Please run th0th_index with projectPath set to the current " +
                "working directory to enable semantic code search.",
            },
          ],
        },
        { deliverAs: "nextTurn", triggerTurn: false },
      );
    }

    ctx.ui.setStatus("th0th", hasIndex ? "\\u2713 indexed" : "\\u26A0 not indexed");
  });
}
`;

// ---------------------------------------------------------------------------
// Slash commands — .omp/commands/*.md
// ---------------------------------------------------------------------------

export const COMMANDS: Record<string, { filename: string; content: string }> = {
  "index-project": {
    filename: "index-project.md",
    content: `---
description: Index the current project for th0th semantic search
---
Index this project for semantic code search. Run th0th_index with:
- projectPath: the current working directory
- forceReindex: \$1
- warmCache: true

After indexing, confirm the index status with th0th_analytics.
`,
  },
  "search-code": {
    filename: "search-code.md",
    content: `---
description: Semantic code search via th0th
---
Search the codebase using th0th semantic search for: \$ARGUMENTS

Use th0th_search with the query above. Show the top 5 results with file paths and relevant code snippets.
`,
  },
  remember: {
    filename: "remember.md",
    content: `---
description: Store a memory in th0th for future sessions
---
Store the following as a persistent memory using th0th_remember: \$ARGUMENTS

Choose the appropriate memory type (decision, pattern, code, preference, or conversation) based on the content.
`,
  },
};
